### ISSUE TITLE
Please state in the minimum requirements that cpg doesn't run on PHP7.0

### ISSUE THREAD

**Issue by jammon** [coppermine-gallery/cpg1.6.x#10]
I found this crucial information in some forum, it should be in the requirements.

**Comment by ron4mac** [comment]
That is not the case, however. Coppermine Photo Gallery version 1.6 does indeed run on PHP7 without issue.

**Comment by jammon** [comment]
Am 05.01.17 um 13:34 schrieb ron4mac:
> That is not the case, however. Coppermine Photo Gallery version 1.6 does
> indeed run on PHP7 without issue.

Ok, probably you're right. But the current version on the download site
is 1.5, that's the version I tried.
I didn't find any other feedback channel, that's why I posted an issue
on github.

Regards, Johannes
