### ISSUE TITLE
Bridge to SMF2

### ISSUE THREAD

**Issue by jimmyfi** [coppermine-gallery/cpg1.6.x#11]
Tested out the new version of php7 and smf2 and Coppermine 1.6. Forum works fine after few tweaks and gallery works out fine but when bridge is enabled i get tons of errors
```
Fatal error: 
Uncaught Error: Call to a member function query() on null in /public_html/gallery/bridge/udb_base.inc.php:59 
Stack trace: 
#0 /public_html/gallery/bridge/udb_base.inc.php(82): core_udb->query('SELECT u.id_mem...') 
#1 /public_html/gallery/include/init.inc.php(257): core_udb->authenticate() 
#2 public_html/gallery/index.php(25): require('...') 
#3 {main} thrown in /public_html/gallery/bridge/udb_base.inc.php on line 59
```
not really sure how to fix this . helps?

**Comment by ron4mac** [comment]
Thanks for the feedback. Bridging has not yet been fully transitioned to 1.6.

I'm on the development team but have no real experience with bridging. Could you please try this:

File: bridge/udb_base.inc.php
change lines:
  30		global $CONFIG, $CPGDB;
  50		$this->dbObj = $CPGDB;

**Comment by jimmyfi** [comment]
Ron4Mac That did the trick and it works as it should now =) Thank you
