### ISSUE TITLE
Cosmetic Fix for Thumbnails that don't add up to 100% width

### ISSUE THREAD

**Issue by pcjonathan** [coppermine-gallery/cpg1.6.x#12]
I'm in cpg1.5, however I noticed the code snippet is the same in cpg1.6 and wanted to contribute it to future versions.

When the screen width is less than the table width, it'll resize down, however this looks a little shitty when the cell widths add up to more than 100% (e.g. 6 columns, get 17% each which is 102% in total)  as the last cell is a fair bit smaller than the rest.

I've fixed this in my copy by changing include/themes.inc.php#L2843 from:

`$cell_width = ceil(100 / $CONFIG['thumbcols']) . '%';`

to

`$cell_width = floor((100 / $CONFIG['thumbcols']) * 100) / 100 . '%';`

Perhaps something to consider in 1.6?

**Comment by ron4mac** [comment]
Thanks much for the suggestion/feedback. Your suggestion has been applied.
