### ISSUE TITLE
Cannot use js_include() or $JS for remote resource

### ISSUE THREAD

**Issue by dpaulat** [coppermine-gallery/cpg1.6.x#14]
Because js_include() always checks file_exists() for the script being included, I am unable to use $JS or js_include for remote resources, e.g., "//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js".

**Comment by ron4mac** [comment]
In what way are you trying to do this?  Are you creating a plugin? a theme?

**Comment by dpaulat** [comment]
I am creating a plugin.

**Comment by ron4mac** [comment]
You can use the _pageheader_ function to add items to the head section:

pageheader('Page Name', '<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" ></script>');

**Comment by dpaulat** [comment]
It is my understanding this can't be used from the config action, as the
page header is built external to this function.

**Comment by ron4mac** [comment]
I'll see about relaxing the local file constraint on _js_include()_. Thanks for your feedback.

**Comment by ron4mac** [comment]
We will be easing that restriction. In the mean time, make the below change to _include/functions.inc.php_ at around line #5395.

```
// Proceed with inclusion only if the local file exists or it is a remote file
if (!(file_exists($filename) || preg_match('|^//[-a-z0-9_.]+/|i', $filename))) {
    return;
}
```
And if you are using the config action method to administer your plugin, calling _js_include()_ to place script in the page head will be ineffective, as _pageheader()_ has already been called. You will have to use the array form of config action to include .js or .css in the page head.

**Comment by ron4mac** [comment]
After further review, it has been determined that using remote resources via a config action array will be an issue until the plugin manager is modified.

**Comment by ron4mac** [comment]
Changes were made to _include/functions.inc.php_ and _pluginmgr.php_ to allow remote resource urls.
You can download these files individually, as they are not yet part of any release.
