### ISSUE TITLE
Album bassword protection

### ISSUE THREAD

**Issue by jflash** [coppermine-gallery/cpg1.6.x#15]
Hello! I am using CPG 1.6.01 and there if i protect gallery with password all users see this category like usual category - nothing is under password :(

**Comment by eenemeenemuu** [comment]
Please explain more detailed which password you mean. Album passwords work as expected. Categories cannot be password protected. Global password for registration only applies to account registration.

**Comment by jflash** [comment]
Sorry, my bad, i was using 1.6.01, after i copy 1.6.03 problem solved! Thank you!
