### ISSUE TITLE
Missing Optional Parameter

### ISSUE THREAD

**Issue by pcjonathan** [coppermine-gallery/cpg1.6.x#18]
Setting up a new install and trying out PDO for the first time. Got this:

 mod_fcgid: stderr: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function checkPdoConnection(), 0 passed in DOMAIN/include/database/pdo/install.php on line 106 and exactly 1 expected in DOMAIN/include/database/pdo/install.php:30, referer: DOMAIN/install.php?step=7

https://github.com/coppermine-gallery/cpg1.6.x/blob/40756c99f9ff8de4419d36c8503cee81024bf3b8/include/database/pdo/install.php#L30

Changing this to `function checkPdoConnection ($sub=null)`, like the others, seemed to fix it. 👍
Cheers

**Comment by ron4mac** [comment]
Thanks for the feedback. Was your install with PHP 7.1+ ?

**Comment by pcjonathan** [comment]
Oh bugger. I knew I forgot to mention something. Yeah, it's PHP 7.2.

**Comment by ron4mac** [comment]
Correction made...
Thank you.
