### ISSUE TITLE
autoorient removes iptc data from image

### ISSUE THREAD

**Issue by tbsmark86** [coppermine-gallery/cpg1.6.x#20]
version: cpg 1.6.03 
image-lib: gd

Possible exif data to. Also JPEG quality settings are changed.

**Comment by ron4mac** [comment]
There will be no way to preserve image meta data when using GD. Use ImageMagick/IMagick or don't select auto-orient. Please fork the repository, then provide a pull request with any changes you feel should be made regarding jpeg quality.
