### ISSUE TITLE
Save new configuration button does not work

### ISSUE THREAD

**Issue by HyperDevil** [coppermine-gallery/cpg1.6.x#21]
Running latest version of CPG from github.
Upgraded from 1.5x, went fine.
Now when changing settings as admin does not work anymore, when pressing "save new configuration" in the gallery configuration nothing seems to happen.
Nothing in the console of my browser.
Any ideas?

*Addon*
Now it seems to change settings but i get no visual feedback*

**Comment by ron4mac** [comment]
Unless you have comments about specific coding issues, please get support via the Coppermine Forum.
http://forum.coppermine-gallery.net/index.php/board,140.0.html
