### ISSUE TITLE
Create official Docker image for CPG

### ISSUE THREAD

**Issue by okainov** [coppermine-gallery/cpg1.6.x#24]
Please create official docker image

**Comment by ron4mac** [comment]
We will not be creating an official docker image.

**Comment by nzbtuxnews** [comment]
+1 for a Docker container for Coppermine. Coppermine is great but is dated, and the competition are all offering a Docker container.  By standardizing the setup across OS'es and architectures, the installation issues & other issues relating to specific configurations would be greatly reduced.  If you look at the forums and Github tickets, 75%+ of the problems are installation issue so the devs would make their lives easier.  Just my 2 cents ;)
