### ISSUE TITLE
Access to private User Files: absolute Path

### ISSUE THREAD

**Issue by whjochim** [coppermine-gallery/cpg1.6.x#28]
In the default webserver config all files in the web-root are accessible, including albums and sub-directories. 
This means, any client, not even logged in, can access the user Pictures, even when the Picture is set to "Only User can see it".
If access to the Directory is disabled, access via displayimage.php is also not possible.
Incrementing UserID's and AlbumID's makes the access easier.

Example: https://coppermine-gallery.net/demo/cpg15x/albums/userpics/10001/normal_ascalaphe_4.jpg

**Comment by ron4mac** [comment]
For those desiring that level of access protection, there is a plugin available.
https://forum.coppermine-gallery.net/index.php/topic,78168.msg378179.html#msg378179
