### ISSUE TITLE
Fatal error: 'break' not in the 'loop' or 'switch' context in /srv/http/blacker/gallerytests/coppermine/include/picmgmt.inc.php on line 547

### ISSUE THREAD

**Issue by TheNumenorean** [coppermine-gallery/cpg1.6.x#3]
Using current version

**Comment by ron4mac** [comment]
Issue correct with merged commits.
https://github.com/coppermine-gallery/cpg1.6.x/commit/1318d6983072c82cad78a437ca463da6098842b6
