### ISSUE TITLE
No LDAP bridge

### ISSUE THREAD

**Issue by bellera** [coppermine-gallery/cpg1.6.x#30]
I was using Coppermine LDAP Bridge v2.0 (for Coppermine version 1.5.18) until 1.5.48. Not compatible with 1.6. It's using obsolete php-mysql and 1.6 uses php-mysqli
LDAP Bridge v2.0 can be found at https://forum.coppermine-gallery.net/index.php?topic=74451.0

**Comment by ron4mac** [comment]
Try this updated file to see if it works for you.

[ldap.inc.php.txt](https://github.com/coppermine-gallery/cpg1.6.x/files/2963459/ldap.inc.php.txt)

**Comment by bellera** [comment]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; cpg_udb has a deprecated constructor in ............................. /bridge/ldap.inc.php on line 37

**Comment by ron4mac** [comment]
Sorry ... missed that.

[ldap.inc.php.txt](https://github.com/coppermine-gallery/cpg1.6.x/files/2963865/ldap.inc.php.txt)

**Comment by ron4mac** [comment]
Please let me know when this is working as expected. I will then add it to the distribution and post it on the Coppermine Forum. Thanks for your help.

**Comment by bellera** [comment]
It works if user exists (at cpg_users). For new Coppermine users (existing in LDAP), something wrong:

Critical error
There was an error while processing a database query

**Comment by bellera** [comment]
Thanks a lot for your help!
