### ISSUE TITLE
Admin cannot create new album even with curve / classic theme

### ISSUE THREAD

**Issue by rivimey** [coppermine-gallery/cpg1.6.x#33]
I have an old CPG which has been updated to 1.6.06 moderately successfully - that is, all ok except that the New Album button just spins its spinner, even when left for 5 mins. Refreshing page shows nothing happened.

I saw there have in the past been similar issues so I made sure that changing theme to "curve" or "classic" didn't help - sadly it did not.

I cannot see any errors (at all) in php logs. 

There was a notice in the browser console about loading google font using http:// when site is on https:, but I've fixed that in the theme.

I have enabled debug output in the maintenance area but there is nothing interesting showing up (it is only reporting things during page generation and this is happening in JS, only).

I do get "Unchecked runtime.lastError: The message port closed before a response was received." in the Chrome console log, but it doesn't help me understand the issue, if any.

**However**, If I enable Network log in Chrome Inspector, I can see that a call to delete.php is made, with the request/response as below. I have pulled out the interesting part here:

`         <form name="dbsql" id="dbsql"><textarea rows="8" cols="60">While executing query 'INSERT INTO cpg1_albums (category, title, uploads, pos, description, owner) VALUES ('0', 'Jans50th', 'NO', '100', '', '1')' in delete.php on line 532
     database error: 1292 : Incorrect datetime value: '0000-00-00 00:00:00' for column 'last_addition' at row 1
     </textarea>< /form>< /span>
     
                        < br />
                        < br />
                        File: /web/html/images/include/functions.inc.php - Line: 250
     
                        <br /><br />
                    </div>
     <script language="javascript" type="text/javascript" >
    
        < /script>
`

Please note that my database is, according to the update script, all ok. and all the files check out ok as well.

Can you help make a fix available?

**Comment by rivimey** [comment]
[cpg_error.txt](https://github.com/coppermine-gallery/cpg1.6.x/files/3174072/cpg_error.txt)

**Comment by rivimey** [comment]
The SQL structure for my album table is:

`
CREATE TABLE `cpg1_albums` (
  `aid` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT '',
  `description` text NOT NULL,
  `visibility` int(11) NOT NULL DEFAULT '0',
  `uploads` enum('YES','NO') NOT NULL DEFAULT 'NO',
  `comments` enum('YES','NO') NOT NULL DEFAULT 'YES',
  `votes` enum('YES','NO') NOT NULL DEFAULT 'YES',
  `pos` int(11) NOT NULL DEFAULT '0',
  `category` int(11) NOT NULL DEFAULT '0',
  `owner` int(11) NOT NULL DEFAULT '1',
  `pic_count` int(11) NOT NULL DEFAULT '0',
  `thumb` int(11) NOT NULL DEFAULT '0',
  `last_addition` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `stat_uptodate` enum('YES','NO') NOT NULL DEFAULT 'NO',
  `keyword` varchar(50) DEFAULT NULL,
  `alb_password_hint` text,
  `alb_password` varchar(32) DEFAULT NULL,
  `moderator_group` int(11) NOT NULL DEFAULT '0',
  `alb_hits` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`aid`),
  KEY `alb_category` (`category`),
  KEY `moderator_group` (`moderator_group`)
) ENGINE=MyISAM AUTO_INCREMENT=43 DEFAULT CHARSET=latin1;`

**Comment by rivimey** [comment]
Workaround:

If I change the default value on the last_addition column to "2000-01-01 00:00:00" I can create the album just fine.

**Comment by ron4mac** [comment]
The _last_addition_ field in the albums table is not a part of any CPG distribution. You must be using some plugin that is causing (has caused) your issue.

**Comment by ron4mac** [comment]
Should you determine which plugin does this, could you please post it here?
