### ISSUE TITLE
Coppermine PHP 7.3 and MySQL 8

### ISSUE THREAD

**Issue by HyperDevil** [coppermine-gallery/cpg1.6.x#40]
Upgraded to Ubuntu 19.10, now coppermine doesnt seem to work:

MySQL config:
/etc/mysql//etc/mysql/mysql.conf.d/mysqld.cnf
default-authentication-plugin=mysql_native_password

Created user this way:
CREATE USER 'jeffrey'@'localhost' IDENTIFIED WITH mysql_native_password BY 'new_password1',

Error:
Fatal error: Uncaught Error: Call to a member function errorInfo() on null in /xxx/xxx/tftggallery/include/database/pdo/dbase.inc.php:71 Stack trace: #0 /xxx/xxx/tftggallery/include/init.inc.php(175): CPG_Dbase->getError() #1 /xxx/xxx/tftggallery/index.php(22): require('/xxx/xxx/tftgg...') #2 {main} thrown in /xxx/xxx/tftggallery/include/database/pdo/dbase.inc.php on line 71

**Comment by ron4mac** [comment]
mysqli is recommended over PDO

but ...

in database/pdo/dbase.inc.php on line 70 change:
`		if (!$last) {`
to 
`		if (!$last && $this->_instance) {`
See if that gives connection error info

**Comment by HyperDevil** [comment]
Hi, i think i found out what the problem is.
From MySQL 8, mysqli and pdo do not support the new MySQL authentication scheme, it's something that was not revertible in my case on Ubuntu 19.10.
I had to download the packages for MySQL 5.7.22, install these with dpkg manually.
After a complete downgrade of MySQL everything works as expected.

So no bug in coppermine, it's pdo and mysqli that are lagging behind the MySQL releases.
