### ISSUE TITLE
modifyalb.php wrong class with tr and td

### ISSUE THREAD

**Issue by heismauri** [coppermine-gallery/cpg1.6.x#41]
The "tableb" and "tableb_alternate" are put in the tr tag instead of the td tag. So, they can't get the padding from the CSS

**Comment by ron4mac** [comment]
.tableb td {padding:0.25em}

**Comment by ron4mac** [comment]
Looking into this a little further, I see your point.
Re-opening...

**Comment by ron4mac** [comment]
See committed [change](https://github.com/coppermine-gallery/cpg1.6.x/commit/95f20bd4df5b394093b310e8e4275c3c1e9a9730)
