### ISSUE TITLE
Search album results to be displayed = category albums [feature request]

### ISSUE THREAD

**Issue by heismauri** [coppermine-gallery/cpg1.6.x#42]
I would like to have the same columns and tags from the categories in the search area.
![searchalbums](https://user-images.githubusercontent.com/47569205/73869711-96422e00-4829-11ea-9b96-c25f122f8eb0.png)
![categoryalbums](https://user-images.githubusercontent.com/47569205/73869721-993d1e80-4829-11ea-8a39-3a9e3259e024.png)

**Comment by ron4mac** [comment]
This is not an issue. You can achieve these sort of visuals with CSS in a custom theme. Please post requests at the [Coppermine Photo Gallery Forum](https://forum.coppermine-gallery.net).
