### ISSUE TITLE
Missing "icon" class on editpic.php / wrong tag for admintool (util.php)

### ISSUE THREAD

**Issue by heismauri** [coppermine-gallery/cpg1.6.x#43]
The image "images/rating.png" in the editpic.php has no class which make them different from all the other icons in the same page, even next to it.

Also, in the admintools I think that using tableh2 is wrong (which is usually used for not so important headings), and I think it should be tableb / tableb_alternate instead.

Thank u

**Comment by ron4mac** [comment]
Cleaned up _editpics_ icons in [this commit](https://github.com/coppermine-gallery/cpg1.6.x/commit/2c26e0e174f0e2fa7599d98e528fc3078a3eaa67).
