### ISSUE TITLE
[FEATURE REQUEST] Captcha for login

### ISSUE THREAD

**Issue by desfire** [coppermine-gallery/cpg1.6.x#44]
Hi,

I have seen captcha is avaliable for registration, comments,etc but not for logins, I think it would be a great idea to implement it on login page as well to prevent DDOS attacks, I know you can limit the amount of failed logins but adding captcha would reduce the amount of tries.

**Comment by realmofevil** [comment]
You could use the free CloudFlare plan for DDoS. Captcha doesn't stop DDoS. I still have hundreds of bots registering per week, in the end, I've disabled the registration last year since almost no people used to register for more than 5 years. :)

**Comment by ron4mac** [comment]
This feature will not be implemented in Coppermine Photo Gallery
