### ISSUE TITLE
Missing class when contact is not available for unregistered users

### ISSUE THREAD

**Issue by heismauri** [coppermine-gallery/cpg1.6.x#47]
The error that is displayed when an unregistered user goes to the contact.php does not have any classes nor a text in the h2 tags.

This is how it looks
![howitlooks](https://user-images.githubusercontent.com/47569205/80399839-dc86b680-8887-11ea-8d13-1e9002d54432.png)

This is how it should look like
![howitshouldlook](https://user-images.githubusercontent.com/47569205/80399842-ddb7e380-8887-11ea-80f4-04cc4f8dd2fb.png)

**Comment by ron4mac** [comment]
Thank you for your contributions. I will implement your changes/corrections in the next few days.

**Comment by ron4mac** [comment]
Correction made
