### ISSUE TITLE
Easy installer: open_basedir restriction in effect

### ISSUE THREAD

**Issue by narcisgarcia** [coppermine-gallery/cpg1.6.x#51]
I've opened script provided as "CPG 1.6 (PHP7) Upgrade/Install Aid" and saved at public httpd directory as "install.php"
When I visit that script, I select:
- Install location: New install in the current directory
- Available Install Packages: CPG Release 1.6.09 (Maintenance release)
and I press "Install selected package"

Warning: fopen(): open_basedir restriction in effect. File(/tmp/cpg_upd_1603643485.zip) is not within the allowed path(s): (/srv/www/example.net/www/site.tree/) in /srv/www/example.net/www/site.tree/public/coppermine/cpg_installer_stub.php on line 229
Warning: fopen(/tmp/cpg_upd_1603643485.zip): failed to open stream: Operation not permitted in /srv/www/example.net/www/site.tree/public/coppermine/cpg_installer_stub.php on line 229
Warning: fwrite() expects parameter 1 to be resource, bool given in /srv/www/example.net/www/site.tree/public/coppermine/cpg_installer_stub.php on line 230
Could not save package file. Operation aborted.

The only content dumped to installer.log.txt is:
GETTING: 1.6.09

Of course PHP service is configured with:
php_admin_value open_basedir /srv/www/example.net/www/site.tree/
(and no other insecure value is feasible)

**Comment by narcisgarcia** [comment]
Another config option of this website:
php_admin_value upload_tmp_dir /srv/www/example.net/www/site.tree/system/tmp/

To fix this bug, this value can be obtained with this PHP function: ini_get('upload_tmp_dir')

**Comment by phill104** [comment]
Hi, you can find the answer and alternate method here - https://forum.coppermine-gallery.net/index.php/topic,79575.msg385801.html#msg385801

**Comment by narcisgarcia** [comment]
I think a better answer to a bug (+fix proposal) is to fix the bug:
Replacing "sys_get_temp_dir()" by "ini_get('upload_tmp_dir')" when it returns an existing path.

No webhosting service allows to write to a system-wide directory.

**Comment by phill104** [comment]
Of course. For that I will allow one of the devs to investigate.

**Comment by ron4mac** [comment]
> No webhosting service allows to write to a system-wide directory.

I don't believe that is correct. I have hosted with at least 8 different (cPanel) hosting plans and none of them have had _open_basedir_ set to some value.

Thank you for pointing us to this situation. I will modify the _cpg_installer_stub_ to be more robust in dealing with it.

BTW: It may not be a good idea to place the installer stub as 'install.php'.

**Comment by ron4mac** [comment]
Attached an updated _cpg_installer_stub_ to the 1.6.09 CPG release.
