### ISSUE TITLE
PHP 7.4 and Issues

### ISSUE THREAD

**Issue by jimmyfi** [coppermine-gallery/cpg1.6.x#52]
Hello there
Firstly Thank you for your hardwork making CPG over ther years and work on new version.

Unfortunately lately I've been getting errors on php 7.4.11 from various things
```

/include/init.inc.phpDeprecated line 61: Function get_magic_quotes_runtime() is deprecated
Notice line 196: Undefined index: log_retention
--
/include/inspekt/cage.phpDeprecated line 735: Function get_magic_quotes_gpc() is deprecated
--
/bridge/udb_base.inc.php

    Deprecated line 383: Function get_magic_quotes_gpc() is deprecated

```
I've run my websites with debug mode on and I've been able to capture those errors.
I wonder if you'd have a fix for those errors? They are not site breaking but I get those same errors on server error log ..

With Kind Regards Jimmyfi

**Comment by ron4mac** [comment]
Please post issues found in current versions only.
Those conditions were addressed a couple of versions ago.
