### ISSUE TITLE
PDO MySQL based installation

### ISSUE THREAD

**Issue by anytizer** [coppermine-gallery/cpg1.6.x#57]
Fatal error: Uncaught Error: Call to undefined function createPdo:mysqlDb() in D:\xampp\htdocs\cpg1.6.x-1.6.12\install.php:414 Stack trace: #0 {main} thrown in D:\xampp\htdocs\cpg1.6.x-1.6.12\install.php on line 414

https://github.com/coppermine-gallery/cpg1.6.x/blob/develop/install.php#L414

**Comment by ron4mac** [comment]
Thank you for your feedback. Needed changes have been made and will be included beginning with CPG 1.6.13
