### ISSUE TITLE
SMF 2.1 bridge does not work

### ISSUE THREAD

**Issue by jimmyfi** [coppermine-gallery/cpg1.6.x#59]
I updated my forum from 2.0.18 to SMF 2.1 RC4 and i tried bridging my galleries to it but it doesnt seem to work.. I tried redo the bridging with 2.1 bridge file. From gallery index php i get transferred to forum frontpage with code 302 when checking with developer tools. Not really sure how i should fix this ..

**Comment by ron4mac** [comment]
The SMF 2.1 bridge file in the repository has been modified to function with SMF 2.1 RC4.  That change is not yet part of a release.  Please see if it functions okay for you.

**Comment by jimmyfi** [comment]
> 
> 
> The SMF 2.1 bridge file in the repository has been modified to function with SMF 2.1 RC4. That change is not yet part of a release. Please see if it functions okay for you.

Works like a charm :) Thank you <3
