### ISSUE TITLE
CPG1.6.x install fails with blank page after DB selection step

### ISSUE THREAD

**Issue by nzbtuxnews** [coppermine-gallery/cpg1.6.x#60]
I already posted on the forums at https://forum.coppermine-gallery.net/index.php/topic,80472.0.html but nevertheless opening up a ticket here in the hope this get fixed as there seems to be tons of people having similar issues.

Basically I am trying to install CPG 1.6.x (git clone) on a Rocky Linux 8 VPS.  The issue I have is that the installer fails at the step where it connects to the database.  Basically, I get a blank page after I click on "Next step".   For information, I use a remote MariaDB server for database storage.

What I've done:

1. Go to /var/www/html and:
```
git clone https://github.com/coppermine-gallery/cpg1.6.x.git
mv cpg1.6.x coppermine
chown -R apache:apache coppermine
```

2. Navigated to https://vps.localdomain/coppermine/install.php

Step 1: License agreement: OK (no problems)

Step 2: Checking installation files: OK  (no problems)
    Displaying 1505 items of 1505 folders/files processed with 0 potential issues

Step 3: Checking directory permissions: OK  (no problems)
    Directory   Status
    ./albums   Writable
    ./albums/userpics   Writable
    ./albums/edit   Writable
    ./include   Writable

Step 4: Image package selection: OK (no problems)
```
Your server supports the following image package(s)
GDlib Version 2.
ImageMagick Version 6.9.10(at: /usr/bin/)
```

Step 5: Testing image library: OK (but for some reasons I have to click "Next step" twice...)

Step 6: Database user authentication

**Remark 1**: Only MYSQLI or PDO:Mysql are available in the dropdown menu.
- I selected "MYSQLI"
- I entered the address of the DB server, username & password (for information, I can connect to the remote MariaDB server using the same credentials via the mysql CLI command)
- I clicked "Test connection" => "Successful connection with database"
- I clicked "Next step"

**I get a BLANK page.**

Surprised no tickets has been filed on Github for these installation issues as the forums are crawling with those.  No errors in apache logs.

php -v
```
PHP 7.2.24 (cli) (built: Oct 22 2019 08:28:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24, Copyright (c) 1999-2018, by Zend Technologies
```

php -m
```
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

hostnamectl
```
 Static hostname: vps.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           Boot ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    Virtualization: kvm
  Operating System: Rocky Linux 8.4 (Green Obsidian)
       CPE OS Name: cpe:/o:rocky:rocky:8.4:GA
            Kernel: Linux 4.18.0-305.25.1.el8_4.x86_64
      Architecture: x86-64
```

I tried with the cpg_install_stub.php script (v3.4) pretty much every possible way (selecting different CPG versions, etc) and I could NEVER make it work past the DB step (sometimes even having other issues).  I'm out of ideas.  CPG 1.6.x seems to be broken?

**Comment by nzbtuxnews** [comment]
Apache VHost (if relevant):
```

<VirtualHost *:80>
        ServerAdmin root@localhost
        DocumentRoot "/var/www/html/coppermine"
        ServerName vps.localdomain

        <Directory "/var/www/html/coppermine/">
                Options MultiViews FollowSymlinks
                AllowOverride All
                Order allow,deny
                Allow from all
        </Directory>

        TransferLog /var/log/httpd/coppermine_access.log
        ErrorLog /var/log/httpd/coppermine_error.log
</VirtualHost>
```

**Comment by ron4mac** [comment]
I believe this has been resolved.
See [CPG Forum](https://forum.coppermine-gallery.net/index.php/topic,80472.msg389263.html#msg389263)
