### ISSUE TITLE
Two registered users cannot rate same image

### ISSUE THREAD

**Issue by MartPhotos** [coppermine-gallery/cpg1.6.x#61]
Using cpg1.6.09 on linux.
We have 2 registered users residing at the same address (i.e. connecting from same IP). When one has logged in and rated an image, when the second logs in under their own user name and navigates to rate the same image as the first they are told "You have already voted for this image".
I think the issue is with line 3625(?) of include/themes.inc.php:

$result_vote_stats = cpg_db_query("SELECT null FROM {$CONFIG['TABLE_VOTE_STATS']} WHERE pid = {$CURRENT_PIC_DATA['pid']} AND ip = '$raw_ip'");

should it have a test for user_id in the where clause?

**Comment by ron4mac** [comment]
It is agreed that the logic of double vote prevention should be changed to allow votes from different users in such a situation. It will be corrected in the next release (1.6.17).

**Comment by ron4mac** [comment]
See [changes made](https://github.com/coppermine-gallery/cpg1.6.x/commit/bbd2ed8428012b6757be5b8b2db1f129bf253880) that resolve this issue.
