### ISSUE TITLE
:shield: Security vulnerabilities

### ISSUE THREAD

**Issue by hitisec** [coppermine-gallery/cpg1.6.x#62]
Hi,
Some potential security vulnerabilities has been identified in this repository.
Please Validate reports submitted on huntr and if are valid please mark them valid there.
The report links are the following:

https://huntr.dev/bounties/1-other-coppermine-gallery/cpg1.6.x/

**Comment by eenemeenemuu** [comment]
Has been fixed in cpg1.6.13

**Comment by hitisec** [comment]
Thanks can you validate in the platform please?
Regards
