### ISSUE TITLE
Deprecated: Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by Dyr-Fenrir** [coppermine-gallery/cpg1.6.x#63]
Greetings,

I get the following error at the top of every page in the gallery:

Deprecated: Automatic conversion of false to array is deprecated in <censored>\gallery\include\debugger.inc.php on line 114

May you help me out fixing this issue please?

Here is more information:

Server: Windows 10 Pro
Apache: 2.4.53
PHP: 8.1.4
MySQL: 8.0.28
Coppermine: 1.6.17 (I did an update from 1.6.06)

Let me know if you need additional information as well.

Thank you for your time and help, it is greatly appreciated.

**Comment by ron4mac** [comment]
CPG has not yet been qualified for PHP 8.1

Replace _**include/debugger.inc.php**_ with the attached
[debugger.inc.php.zip](https://github.com/coppermine-gallery/cpg1.6.x/files/8317934/debugger.inc.php.zip)

**Comment by Dyr-Fenrir** [comment]
Ah ok, thank you, it makes sense now, thank you as well for the modified file, if I see other issues, I will wait for an official release for 8.1, it is greatly appreciated.
