### ISSUE TITLE
IPv6 banning

### ISSUE THREAD

**Issue by jc42jc** [coppermine-gallery/cpg1.6.x#67]
Hello,
I have the impress that the banning feature is not working with IPv6 users. 
Today our galerie wasn't accesible for all users. In the banned table I find 0.0.0.0 in the source IP.

Our version is 1.6.16

In the code I can find an IPv4 regex.

`        $post_temp_array = $superCage->post->getMatched('ip_addr_'.$posted_ban_id, '/^\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b$/') ?: [null];
        $post_ip         = $post_temp_array[0];
`

**Comment by jc42jc** [comment]
in inspekt.php the function isIp is not compatible with IPV6 too.

https://www.php.net/manual/fr/function.ip2long.php


`
    public static function isIp($value)
    {
        return (bool) ip2long($value);
    }
`

**Comment by jc42jc** [comment]
Hello,
It's linked to this pull request.

https://github.com/coppermine-gallery/cpg1.6.x/pull/70

**Comment by ron4mac** [comment]
Thank you for your feedback. Changes have been committed.
https://github.com/coppermine-gallery/cpg1.6.x/commit/51478573d9b610a3e176a59c1770337b48274355
