### ISSUE TITLE
Fix for bridge to vBulletin with custom MySQL port

### ISSUE THREAD

**Issue by smeeus** [coppermine-gallery/cpg1.6.x#7]
I have been running a website with a Coppermine 1.5 to vBulletin bridge integration for over 10 years now. I recently switched to a HAProxy setup for my MySQL connections, running on a different port then the standard 3306.
This doesn't work with the current Coppermine vBulletin bridge, unless the following fix is applied to bridge/vbulletin30.inc.php (line 64)

```
64c64
<                     'host' => $config['MasterServer']['servername'] ? $config['MasterServer']['servername'] : 'localhost',
---
>                     'host' => $config['MasterServer']['servername'] ? $config['MasterServer']['servername'] . ($config['MasterServer']['port'] ? ':' . $config['MasterServer']['port'] : ':3306') : 'localhost' . ($config['MasterServer']['port'] ? ':' . $config['MasterServer']['port'] : ':3306'),
207c207
```

It would be nice to see this implemented, not only in 1.6 but also backported to 1.5.

I would assume the same fix could also be applied to other bridges, I leave it at your discretion to implement those.

**Comment by ron4mac** [comment]
Thank you for pointing this out to us. Code has been added to the vBulletin bridge to accommodate an alternate dbase port.
