### ISSUE TITLE
Corrupted EXIF data causes exception thrown from displayimage.php

### ISSUE THREAD

**Issue by kaesa** [coppermine-gallery/cpg1.6.x#71]
Hello

Function unRational($data, $type, $intel) - (include/exif.php:542) returns string $top.'/'.$bottom when the $top has value and the $bottom is 0. This is an issue at least for EXIF tags '011a' and '011b', XResolution and YResolution, when rounding the returned value at line 615 (include/exif.php).

Changing the return value to integer 0 for that particular case solved my specific problem. I'm not familiar with EXIF or the code here to know if that is sufficient or bad.

PHP version 8.2.

**Comment by ron4mac** [comment]
Could you please attach an image file that causes the failure?

**Comment by kaesa** [comment]
![20180622_225000](https://user-images.githubusercontent.com/9120965/222474427-c99e007c-281d-405e-a14e-6481d1c6f8ad.jpg)

Also note, reading the  EXIF data must be enabled in the settings to reproduce the problem.

**Comment by kaesa** [comment]
I will also add to anyone testing this, once the exif data has been succesfully read, it is inserted into the database and read from there every time after that. So it must be deleted from table "cpg16x_exif" while testing. I don't know any other method but doing it manually.

**Comment by ron4mac** [comment]
Thank you for your feedback. The include/exif.php file has been corrected for this issue. [See commit.](https://github.com/coppermine-gallery/cpg1.6.x/commit/9313de51339bcc29a5d5655383a48c95cc377e9e)
