### ISSUE TITLE
Type mismatch in makers/nikon.php

### ISSUE THREAD

**Issue by m707** [coppermine-gallery/cpg1.6.x#73]
I am no coder, but after updating my bullseye box (php7.4) to bookworm (php8.2) I noticed that some images did not work anymore:

`Unsupported operand types: string / int in /var/www/fotos/include/makers/nikon.php:342 `

No idea if it is the right fix, but after changing line 342 from:

`$data = $data / 100;`

to:

`$data = (int)$data / 100;`

everything seems to work again. HTH.

**Comment by ron4mac** [comment]
Thank you for the feedback. Corrected for version 1.6.26
