### ISSUE TITLE
No more load image after update to 1.6

### ISSUE THREAD

**Issue by ik2djy** [coppermine-gallery/cpg1.6.x#74]
Hi,
after updated the gallery form 1.5 to 1.6 when I load images to album, I got this error: '"Image_1.jpg
Call to undefined function exec() 
/include/imageobject_im.class.php line:350
Any Idea how to fix it?
Thanks
Regards

Giuliano

**Comment by ron4mac** [comment]
The version of PHP that you are using with CPG 1.6.x needs to have the _exec()_ function enabled.

**Comment by ik2djy** [comment]
Hi,
Done, solved
Thanks

Giuliano

Il giorno lun 3 giu 2024 alle 04:31 ron4mac ***@***.***> ha
scritto:
