### ISSUE TITLE
MySQLi said: 2054 : Server sent charset unknown to the client. Please, report to the developers

### ISSUE THREAD

**Issue by PegWeb** [coppermine-gallery/cpg1.6.x#78]
Our host upgraded our MySQL to 8.x and since then we could not get the gallery site to load. We downloaded the newest version of Coppermine 1.6.x and try to run the update.php but we get

Coppermine critical error:
Unable to connect to database !

MySQLi said: 2054 : Server sent charset unknown to the client. Please, report to the developers

**Comment by phill104** [comment]
Please could you open a thread on our support forum at coppermine-gallery.com 

There is a lot more information we would need to help you upgrade and it is better placed in the forum

**Comment by PegWeb** [comment]
I have. The subject of the post is "Unable to connect to database !"

**Comment by phill104** [comment]
As per your forum post, this appears to have been a hosting related issue so I will close the thread here. If you are still having issues we will be happy to help in the forum.
